FROM golang:1.17 AS build

WORKDIR /source

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o bin/garden cmd/garden/main.go

FROM debian

COPY --from=build /source/bin/garden /garden
ENTRYPOINT ["/garden"]
