---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: concourse-k8s-worker-garden

rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: concourse-k8s-worker-garden

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concourse-k8s-worker-garden

subjects:
  - kind: ServiceAccount
    name: concourse-k8s-worker
