---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: baggageclaim.worker.k8s.concourse-ci.org
  labels:
    app.kubernetes.io/name: worker.k8s.concourse-ci.org
    app.kubernetes.io/component: csi-driver

spec:
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
