---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: concourse-worker.baggageclaim-csi-driver.baggageclaim-csi-driver-policy

spec:
  allowedHostPaths:
    - pathPrefix: /var/lib/kubelet/plugins_registry/
      readOnly: false
    - pathPrefix: /var/lib/kubelet/plugins/baggageclaim.worker.k8s.concourse-ci.org/
      readOnly: false
    - pathPrefix: /var/lib/kubelet/pods
      readOnly: false
    - pathPrefix: /var/lib/baggageclaim.worker.k8s.concourse-ci.org-data
      readOnly: false

  privileged: true

  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny

  volumes:
    - configMap
    - hostPath
    - projected
    - secret

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod.concourse-k8s-pod.concourse-k8s-pod-policy

spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny

  privileged: false
  allowPrivilegeEscalation: true
  allowedCapabilities: ['*']

  volumes:
    - configMap
    - csi
    - emptyDir
    - projected
