---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: baggageclaim-csi-driver-security-policy

rules:
  - apiGroups: [policy]
    resourceNames: [concourse-worker.baggageclaim-csi-driver.baggageclaim-csi-driver-policy]
    resources: [podsecuritypolicies]
    verbs: [use]

  - apiGroups: [""]
    resources: [configmaps, pods]
    verbs: [create, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baggageclaim-csi-driver-security-policy

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: baggageclaim-csi-driver-security-policy

subjects:
  - kind: ServiceAccount
    name: concourse-k8s-worker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: concourse-k8s-pod-security-policy

rules:
  - apiGroups: [policy]
    resourceNames: [pod.concourse-k8s-pod.concourse-k8s-pod-policy]
    resources: [podsecuritypolicies]
    verbs: [use]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: concourse-k8s-pod-security-policy

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: concourse-k8s-pod-security-policy

subjects:
  - kind: ServiceAccount
    name: concourse-k8s-worker
